exports.images = {
  'BLUE': require('../../stimuli/BLUE/BLUE_CHR.svg'),
  'BLUE_CHR.svg': require('../../stimuli/BLUE/BLUE_CHR.svg'),
  'BLUE_CHR-1.svg':require('../../stimuli/BLUE/BLUE_CHR-1.svg'),
  'BLUE_CHR-2.svg': require('../../stimuli/BLUE/BLUE_CHR-2.svg'),
  'BLUE_CHR+1.svg': require('../../stimuli/BLUE/BLUE_CHR+1.svg'),
  'BLUE_CHR+2.svg': require('../../stimuli/BLUE/BLUE_CHR+2.svg'),
  'BLUE_HUE.svg': require('../../stimuli/BLUE/BLUE_HUE.svg'),
  'BLUE_HUE-1.svg':require('../../stimuli/BLUE/BLUE_HUE-1.svg'),
  'BLUE_HUE-2.svg': require('../../stimuli/BLUE/BLUE_HUE-2.svg'),
  'BLUE_HUE+1.svg': require('../../stimuli/BLUE/BLUE_HUE+1.svg'),
  'BLUE_HUE+2.svg': require('../../stimuli/BLUE/BLUE_HUE+2.svg'),
  'BLUE_LUM.svg': require('../../stimuli/BLUE/BLUE_LUM.svg'),
  'BLUE_LUM-1.svg':require('../../stimuli/BLUE/BLUE_LUM-1.svg'),
  'BLUE_LUM-2.svg': require('../../stimuli/BLUE/BLUE_LUM-2.svg'),
  'BLUE_LUM+1.svg': require('../../stimuli/BLUE/BLUE_LUM+1.svg'),
  'BLUE_LUM+2.svg': require('../../stimuli/BLUE/BLUE_LUM+2.svg'),
  'RED_CHR.svg': require('../../stimuli/RED/RED_CHR.svg'),
  'RED_CHR-1.svg':require('../../stimuli/RED/RED_CHR-1.svg'),
  'RED_CHR-2.svg': require('../../stimuli/RED/RED_CHR-2.svg'),
  'RED_CHR+1.svg': require('../../stimuli/RED/RED_CHR+1.svg'),
  'RED_CHR+2.svg': require('../../stimuli/RED/RED_CHR+2.svg'),
  'RED_HUE.svg': require('../../stimuli/RED/RED_HUE.svg'),
  'RED_HUE-1.svg':require('../../stimuli/RED/RED_HUE-1.svg'),
  'RED_HUE-2.svg': require('../../stimuli/RED/RED_HUE-2.svg'),
  'RED_HUE+1.svg': require('../../stimuli/RED/RED_HUE+1.svg'),
  'RED_HUE+2.svg': require('../../stimuli/RED/RED_HUE+2.svg'),
  'RED_LUM.svg': require('../../stimuli/RED/RED_LUM.svg'),
  'RED_LUM-1.svg':require('../../stimuli/RED/RED_LUM-1.svg'),
  'RED_LUM-2.svg': require('../../stimuli/RED/RED_LUM-2.svg'),
  'RED_LUM+1.svg': require('../../stimuli/RED/RED_LUM+1.svg'),
  'RED_LUM+2.svg': require('../../stimuli/RED/RED_LUM+2.svg'),
  'GREEN_CHR.svg': require('../../stimuli/GREEN/GREEN_CHR.svg'),
  'GREEN_CHR-1.svg':require('../../stimuli/GREEN/GREEN_CHR-1.svg'),
  'GREEN_CHR-2.svg': require('../../stimuli/GREEN/GREEN_CHR-2.svg'),
  'GREEN_CHR+1.svg': require('../../stimuli/GREEN/GREEN_CHR+1.svg'),
  'GREEN_CHR+2.svg': require('../../stimuli/GREEN/GREEN_CHR+2.svg'),
  'GREEN_HUE.svg': require('../../stimuli/GREEN/GREEN_HUE.svg'),
  'GREEN_HUE-1.svg':require('../../stimuli/GREEN/GREEN_HUE-1.svg'),
  'GREEN_HUE-2.svg': require('../../stimuli/GREEN/GREEN_HUE-2.svg'),
  'GREEN_HUE+1.svg': require('../../stimuli/GREEN/GREEN_HUE+1.svg'),
  'GREEN_HUE+2.svg': require('../../stimuli/GREEN/GREEN_HUE+2.svg'),
  'GREEN_LUM.svg': require('../../stimuli/GREEN/GREEN_LUM.svg'),
  'GREEN_LUM-1.svg':require('../../stimuli/GREEN/GREEN_LUM-1.svg'),
  'GREEN_LUM-2.svg': require('../../stimuli/GREEN/GREEN_LUM-2.svg'),
  'GREEN_LUM+1.svg': require('../../stimuli/GREEN/GREEN_LUM+1.svg'),
  'GREEN_LUM+2.svg': require('../../stimuli/GREEN/GREEN_LUM+2.svg'),
  'YELLOW_CHR.svg': require('../../stimuli/YELLOW/YELLOW_CHR.svg'),
  'YELLOW_CHR-1.svg':require('../../stimuli/YELLOW/YELLOW_CHR-1.svg'),
  'YELLOW_CHR-2.svg': require('../../stimuli/YELLOW/YELLOW_CHR-2.svg'),
  'YELLOW_CHR+1.svg': require('../../stimuli/YELLOW/YELLOW_CHR+1.svg'),
  'YELLOW_CHR+2.svg': require('../../stimuli/YELLOW/YELLOW_CHR+2.svg'),
  'YELLOW_HUE.svg': require('../../stimuli/YELLOW/YELLOW_HUE.svg'),
  'YELLOW_HUE-1.svg':require('../../stimuli/YELLOW/YELLOW_HUE-1.svg'),
  'YELLOW_HUE-2.svg': require('../../stimuli/YELLOW/YELLOW_HUE-2.svg'),
  'YELLOW_HUE+1.svg': require('../../stimuli/YELLOW/YELLOW_HUE+1.svg'),
  'YELLOW_HUE+2.svg': require('../../stimuli/YELLOW/YELLOW_HUE+2.svg'),
  'YELLOW_LUM.svg': require('../../stimuli/YELLOW/YELLOW_LUM.svg'),
  'YELLOW_LUM-1.svg':require('../../stimuli/YELLOW/YELLOW_LUM-1.svg'),
  'YELLOW_LUM-2.svg': require('../../stimuli/YELLOW/YELLOW_LUM-2.svg'),
  'YELLOW_LUM+1.svg': require('../../stimuli/YELLOW/YELLOW_LUM+1.svg'),
  'YELLOW_LUM+2.svg': require('../../stimuli/YELLOW/YELLOW_LUM+2.svg')
}